### ISSUE TITLE
"Introduction" and "Conclusions" chapters should be numbered

### ISSUE THREAD

**Issue by gszasz** [sars1492/diplomovka#16]
According [Department of Biotechnologies guidelines](http://files.katedra-biotechnologii.webnode.sk/200000430-494734a410/%C5%A0abl%C3%B3ny%20zavere%C4%8Dn%C3%BDch%20pr%C3%A1c.docx), the *Introduction* and *Conclusions* chapters has to be numbered. The thesis look actually better when *Introduction* and *Conclusions* chapters are not numbered, so this might not be a strict requirement and it needs to be discussed with supervisor first. If supervisor confirms that this is not an actual requirement, this bug can be closed with label *invalid*.

**Comment by gszasz** [comment]
@sars1492 I'm moving this issue to future release.

**Comment by sars1492** [comment]
This bug is obsolete.
